# Jabez Magomere 91279

In [1]:
import numpy as np
import pandas as pd

In [2]:
wine = pd.read_table('wine.data',delimiter=',',names = ['Cultivator','Alcohol','Malic_Acid','Ash','Alcalinity_of_Ash','Magnesium','Total_phenols','Falvanoids','Nonflavanoid_phenols','Proanthocyanins','Color_intensity','Hue','OD280','Proline'])

In [4]:
wine.head(10)

Cultivator  Alcohol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1    14.23        1.71  2.43               15.6        127   
1           1    13.20        1.78  2.14               11.2        100   
2           1    13.16        2.36  2.67               18.6        101   
3           1    14.37        1.95  2.50               16.8        113   
4           1    13.24        2.59  2.87               21.0        118   
5           1    14.20        1.76  2.45               15.2        112   
6           1    14.39        1.87  2.45               14.6         96   
7           1    14.06        2.15  2.61               17.6        121   
8           1    14.83        1.64  2.17               14.0         97   
9           1    13.86        1.35  2.27               16.0         98   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   
5           3.27        3.39                  0.34             1.97   
6           2.50        2.52                  0.30             1.98   
7           2.60        2.51                  0.31             1.25   
8           2.80        2.98                  0.29             1.98   
9           2.98        3.15                  0.22             1.85   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735  
5             6.75  1.05   2.85     1450  
6             5.25  1.02   3.58     1290  
7             5.05  1.06   3.58     1295  
8             5.20  1.08   2.85     1045  
9             7.22  1.01   3.55     1045

In [25]:
wine.tail(5)

Cultivator  Alcohol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
173           3    13.71        5.65  2.45               20.5         95   
174           3    13.40        3.91  2.48               23.0        102   
175           3    13.27        4.28  2.26               20.0        120   
176           3    13.17        2.59  2.37               20.0        120   
177           3    14.13        4.10  2.74               24.5         96   

     Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color_intensity   Hue  OD280  Proline  
173              7.7  0.64   1.74      740  
174              7.3  0.70   1.56      750  
175             10.2  0.59   1.56      835  
176              9.3  0.60   1.62      840  
177              9.2  0.61   1.60      560

In [5]:
wine.describe().transpose()

count        mean         std     min       25%  \
Cultivator            178.0    1.938202    0.775035    1.00    1.0000   
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity_of_Ash     178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_phenols         178.0    2.295112    0.625851    0.98    1.7425   
Falvanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Cultivator              2.000    3.0000     3.00  
Alcohol                13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Alcalinity_of_Ash      19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_phenols           2.355    2.8000     3.88  
Falvanoids              2.135    2.8750     5.08  
Nonflavanoid_phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [6]:
X = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [11]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
StandardScaler(copy=True,with_mean=True,with_std=True)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
from sklearn.neural_network import MLPClassifier

In [15]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [16]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [17]:
predictions = mlp.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
print(confusion_matrix(y_test,predictions))

[[18  0  0]
 [ 0 17  0]
 [ 0  0 10]]


In [20]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        17
          3       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        45



In [21]:
len(mlp.coefs_)

4

In [22]:
len(mlp.coefs_[0])

13

In [23]:
len(mlp.intercepts_[0])

13

In [24]:
mlp.coefs_

[array([[-0.18412507, -0.20802275, -0.35689238,  0.10691113,  0.1245151 ,
          0.65979077, -0.17057061,  0.47335011,  0.14163082, -0.15854742,
          0.28176489, -0.39241085,  0.46615252],
        [-0.14898306, -0.42753726,  0.30190575,  0.01686686,  0.29348942,
          0.31606086,  0.39612422, -0.02027957, -0.24102878, -0.06527701,
         -0.11374916,  0.03044061, -0.13844372],
        [ 0.09955255, -0.50254262, -0.39795063,  0.23675364, -0.01431115,
         -0.20104061, -0.22917996,  0.39469549,  0.34801746,  0.51516064,
          0.41489556,  0.32272097,  0.51107496],
        [-0.2631875 ,  0.18276767,  0.04517437,  0.26249715, -0.17659156,
         -0.66811117,  0.39428821, -0.22654458,  0.14163088,  0.35625265,
          0.16182901, -0.22102314,  0.09851108],
        [ 0.1693198 ,  0.25404464, -0.33908528,  0.49453998, -0.35336666,
          0.29343321,  0.22917137,  0.14968333, -0.35003445,  0.18380029,
          0.33392201, -0.06251053, -0.01749681],
        [-0.071